<h6>Giá đất theo Hệ số K được áp dụng:</h6>
1. Khi xác định giá trị thửa đất hoặc khu đất có giá trị dưới 20 tỷ đồng (tính theo giá đất trong bảng giá đất) thì áp dụng hệ số K để thực hiện:<br>
a) Tính tiền sử dụng đất khi Nhà nước công nhận quyền sử dụng đất của hộ gia đình, cá nhân đối với phần diện tích đất ở vượt hạn mức; cho phép chuyển mục đích sử dụng đất từ đất nông nghiệp, đất phi nông nghiệp không phải là đất ở sang đất ở đối với phần diện tích vượt hạn mức giao đất ở cho hộ gia đình, cá nhân. Tính tiền thuê đất đối với đất nông nghiệp vượt hạn mức giao đất, vượt hạn mức nhận chuyển quyền sử dụng đất nông nghiệp của hộ gia đình, cá nhân;<br>
b) Tính tiền sử dụng đất khi Nhà nước giao đất có thu tiền sử dụng đất không thông qua hình thức đấu giá quyền sử dụng đất; công nhận quyền sử dụng đất, cho phép chuyển mục đích sử dụng đất đối với tổ chức mà phải nộp tiền sử dụng đất;<br>
c) Tính tiền thuê đất đối với trường hợp Nhà nước cho thuê đất không thông qua hình thức đấu giá quyền sử dụng đất;<br>
d) Xác định giá trị quyền sử dụng đất (giao, thuê) để tính vào giá trị doanh nghiệp khi cổ phần hóa doanh nghiệp nhà nước mà doanh nghiệp cổ phần hóa sử dụng đất thuộc trường hợp Nhà nước giao đất có thu tiền sử dụng đất, cho thuê đất trả tiền thuê đất một lần cho cả thời gian thuê; tính tiền thuê đất đối với trường hợp doanh nghiệp nhà nước thực hiện cổ phần hóa mà được Nhà nước cho thuê đất trả tiền thuê đất hàng năm;<br>
đ) Xác định lại giá đất cụ thể để tính tiền thuê đất tại thời điểm có quyết định cho phép chuyển sang thuê đất theo hình thức trả tiền thuê đất một lần của tổ chức kinh tế, tổ chức sự nghiệp công lập tự chủ tài chính, hộ gia đình, cá nhân, người Việt Nam định cư ở nước ngoài, doanh nghiệp có vốn đầu tư nước ngoài đang được Nhà nước cho thuê đất trả tiền thuê đất hàng năm nay chuyển sang thuê đất trả tiền thuê đất một lần cho cả thời gian thuê;<br>
e) Xác định lại giá đất cụ thể khi người mua tài sản được Nhà nước tiếp tục cho thuê đất trong thời hạn sử dụng đất còn lại, sử dụng đất đúng mục đích đã được xác định trong dự án;<br>
g) Xác định tiền nhận chuyển nhượng quyền sử dụng đất được trừ vào tiền sử dụng đất, tiền thuê đất phải nộp.<br>
h) Xác định giá khởi điểm để đấu giá quyền sử dụng đất đối với trường hợp nhà nước giao đất có thu tiền sử dụng đất, cho thuê đất thu tiền thuê đất một lần cho cả thời gian thuê.
2. Thuê đất thu tiền hàng năm mà phải xác định lại đơn giá thuê đất để điều chỉnh cho chu kỳ tiếp theo.<br>
3. Xác định giá khởi điểm để đấu giá quyền sử dụng đất khi Nhà nước cho thuê đất thu tiền thuê đất hàng năm
